import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import logo from "../assets/images/logo.jpg";
import Link from "next/link";
import style from "../assets/styles/Home.module.css";
import { HiOutlineSearch } from "react-icons/hi";
import { MdOutlineFavoriteBorder } from "react-icons/md";
import { BsCart4 } from "react-icons/bs";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={style.container}>
        <header className="py-1">
          <nav className="flex gap-4">
            <ul className="flex">
              <li className="w-20">
                <Link href={"/"}>
                  <a>
                    <Image src={logo} />
                  </a>
                </Link>
              </li>
            </ul>
            <ul className="flex flex-1 justify-center gap-8 mt-6 uppercase">
              <li>
                <Link href={"/"}>Home</Link>
              </li>
              <li>
                <Link href={"/"}>Shop</Link>
              </li>
              <li>
                <Link href={"/"}>Blog</Link>
              </li>
              <li>
                <Link href={"/"}>Subscribe</Link>
              </li>
              <li>
                <Link href={"/"}>Samples</Link>
              </li>
            </ul>
            <ul className="flex mt-6">
              <li>
                <Link href={"/"}>
                  <HiOutlineSearch />
                </Link>
              </li>
              <li>
                <Link href={"/"}>
                  <MdOutlineFavoriteBorder />
                </Link>
              </li>
              <li>
                <Link href={"/"}>
                  <BsCart4 />
                </Link>
              </li>
            </ul>
          </nav>
        </header>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
